/** Submissions domain: notes, extraction bookkeeping, proposals, and note↔track links. */

export { NotesError, isNotesError } from "./errors";
export {
  createNote,
  getNoteById,
  listNotes,
  updateNote,
  requeueExtraction,
  completeExtraction,
  failExtraction,
  startAgentRun,
  attachWorkflowRunId,
  finishAgentRun,
  listAgentRunsForNote,
  upsertTransitionCommit,
  getTransitionCommitByKey,
  MAX_SUBMISSION_RAW_BYTES,
  type CreateNoteInput,
  type ListNotesInput,
  type ListNotesResult,
  type NoteListItem,
  type NoteProposalLink,
  type UpdateNoteInput,
  type UpdateNoteResult,
  type CompleteExtractionInput,
  type StartAgentRunInput,
  type FinishAgentRunInput,
  type UpsertTransitionCommitInput,
} from "./notes";
export {
  claimProposal,
  getProposalByKey,
  getProposalById,
  getProposalsByIds,
  listProposalsForVersion,
  listProposals,
  getProposalDetail,
  updateProposal,
  updateProposalGuarded,
  insertProposalReviewEvent,
  refreshSubmissionExtractionStatus,
  supersedeProposalsForNote,
  countProposalsForVersion,
  deriveSubmissionExtractionStatus,
  type ClaimProposalInput,
  type ClaimProposalResult,
  type ListProposalsInput,
  type ListProposalsResult,
  type ProposalDetail,
  type ProposalDetailNote,
  type UpdateProposalInput,
  type UpdateProposalGuardedInput,
  type InsertProposalReviewEventInput,
  type ProposalStatusCounts,
} from "./proposals";
export {
  addNoteTrackLink,
  listNoteTrackLinks,
  listNoteTrackLinksWithTracks,
  removeNoteTrackLink,
  type AddNoteTrackLinkInput,
  type NoteTrackLinkWithTrack,
} from "./note-track-links";
