/** Postgres client + notes + music-domain schema (single-user MVP; membership deferred). */

export { getDb, getDbStatus, isPostgresConfigured, type DbStatus } from "./client";
export { getExecutor, runInDbTransaction, type DbLike } from "./executor";
export { NotesError, isNotesError } from "./errors";
export {
  createNote,
  getNoteById,
  listNotes,
  updateNote,
  requeueExtraction,
  completeExtraction,
  failExtraction,
  startAgentRun,
  attachWorkflowRunId,
  finishAgentRun,
  listAgentRunsForNote,
  upsertTransitionCommit,
  getTransitionCommitByKey,
  MAX_SUBMISSION_RAW_BYTES,
  type CreateNoteInput,
  type ListNotesInput,
  type ListNotesResult,
  type NoteListItem,
  type NoteProposalLink,
  type UpdateNoteInput,
  type UpdateNoteResult,
  type CompleteExtractionInput,
  type StartAgentRunInput,
  type FinishAgentRunInput,
  type UpsertTransitionCommitInput,
} from "./notes";
export {
  claimProposal,
  getProposalByKey,
  getProposalById,
  getProposalsByIds,
  listProposalsForVersion,
  updateProposal,
  supersedeProposalsForNote,
  countProposalsForVersion,
  deriveSubmissionExtractionStatus,
  type ClaimProposalInput,
  type ClaimProposalResult,
  type UpdateProposalInput,
  type ProposalStatusCounts,
} from "./proposals";
export {
  addNoteTrackLink,
  listNoteTrackLinks,
  listNoteTrackLinksWithTracks,
  removeNoteTrackLink,
  type AddNoteTrackLinkInput,
  type NoteTrackLinkWithTrack,
} from "./note-track-links";
export * from "./schema";
export {
  normalizeName,
  FOLDER_KINDS,
  TRANSITION_INTENTS,
  TRANSITION_TECHNIQUES,
  isFolderKind,
  isTransitionIntent,
  isTransitionTechnique,
  MusicWriteError,
  isMusicWriteError,
  DEFAULT_LIST_LIMIT,
  MAX_LIST_LIMIT,
  clampListLimit,
  clampListOffset,
  assertFolderKind,
  ensureArtist,
  ensureGenre,
  ensureSubgenre,
  ensureFolder,
  createTrack,
  listTracks,
  getTrackById,
  getTrackByExternalId,
  getLibraryStats,
  getTrackSummariesByIds,
  asTransitionEdge,
  transitionQualityRank,
  compareNeighborhoodNeighbors,
  rankNeighborhoodNeighbors,
  getTrackNeighborhood,
  createTransition,
  getTransitionById,
  listTransitions,
  updateTransitionById,
  deleteTransitionById,
  commitTransitionProposal,
  commitTransitionProposals,
  type TransitionIntent,
  type TransitionTechnique,
  type ListPageMeta,
  type NamedRef,
  type FolderRef,
  type TrackExternalIds,
  type CreateTrackInput,
  type NamedNode,
  type FolderNode,
  type TrackNode,
  type TrackSummary,
  type TrackDetail,
  type CreateTrackResult,
  type LibraryStats,
  type TrackSortField,
  type ListSortOrder,
  type ListTracksInput,
  type ListTracksResult,
  type TransitionEdgeSummary,
  type NeighborhoodNeighbor,
  type TrackNeighborhood,
  type TransitionEndpointSummary,
  type TransitionRecord,
  type TransitionProposalReview,
  type TransitionListItem,
  type CreateTransitionInput,
  type UpdateTransitionInput,
  type TransitionSortField,
  type TransitionSortOrder,
  type TransitionSourceFilter,
  type ListTransitionsInput,
  type ListTransitionsResult,
  type CommitTransitionInput,
  type CommitTransitionResult,
} from "./music";
