/** Postgres client + notes + music-domain schema (single-user MVP; membership deferred). */

export { getDb, getDbStatus, isPostgresConfigured, type DbStatus } from "./client";
export { getExecutor, runInDbTransaction, type DbLike } from "./executor";
export { NotesError, isNotesError } from "./errors";
export {
  createNote,
  getNoteById,
  listNotes,
  updateNote,
  requeueExtraction,
  completeExtraction,
  failExtraction,
  startAgentRun,
  attachWorkflowRunId,
  finishAgentRun,
  listAgentRunsForNote,
  upsertTransitionCommit,
  getTransitionCommitByKey,
  MAX_SUBMISSION_RAW_BYTES,
  type CreateNoteInput,
  type ListNotesInput,
  type ListNotesResult,
  type NoteListItem,
  type NoteProposalLink,
  type UpdateNoteInput,
  type UpdateNoteResult,
  type CompleteExtractionInput,
  type StartAgentRunInput,
  type FinishAgentRunInput,
  type UpsertTransitionCommitInput,
} from "./notes";
export {
  claimProposal,
  getProposalByKey,
  getProposalById,
  getProposalsByIds,
  listProposalsForVersion,
  listProposals,
  getProposalDetail,
  updateProposal,
  updateProposalGuarded,
  insertProposalReviewEvent,
  refreshSubmissionExtractionStatus,
  supersedeProposalsForNote,
  countProposalsForVersion,
  deriveSubmissionExtractionStatus,
  type ClaimProposalInput,
  type ClaimProposalResult,
  type ListProposalsInput,
  type ListProposalsResult,
  type ProposalDetail,
  type ProposalDetailNote,
  type UpdateProposalInput,
  type UpdateProposalGuardedInput,
  type InsertProposalReviewEventInput,
  type ProposalStatusCounts,
} from "./proposals";
export {
  addNoteTrackLink,
  listNoteTrackLinks,
  listNoteTrackLinksWithTracks,
  removeNoteTrackLink,
  type AddNoteTrackLinkInput,
  type NoteTrackLinkWithTrack,
} from "./note-track-links";
export * from "./schema";
export {
  normalizeName,
  FOLDER_KINDS,
  BLOCK_KINDS,
  GAP_STATES,
  SEQUENCE_MAX_NESTING_DEPTH,
  TRANSITION_INTENTS,
  TRANSITION_TECHNIQUES,
  isFolderKind,
  isBlockKind,
  isGapState,
  isTransitionIntent,
  isTransitionTechnique,
  MusicWriteError,
  isMusicWriteError,
  sequenceMusicWriteStatus,
  DEFAULT_LIST_LIMIT,
  MAX_LIST_LIMIT,
  clampListLimit,
  clampListOffset,
  assertFolderKind,
  ensureArtist,
  ensureGenre,
  ensureSubgenre,
  ensureFolder,
  listGenres,
  listSubgenres,
  listFolders,
  createTrack,
  listTracks,
  getTrackById,
  getTrackByExternalId,
  getLibraryStats,
  getTrackSummariesByIds,
  updateTrackById,
  deleteTrackById,
  asTransitionEdge,
  transitionQualityRank,
  compareNeighborhoodNeighbors,
  rankNeighborhoodNeighbors,
  getTrackNeighborhood,
  createTransition,
  getTransitionById,
  listTransitions,
  updateTransitionById,
  deleteTransitionById,
  commitTransitionProposal,
  commitTransitionProposals,
  countTransitionsBetween,
  type TransitionIntent,
  type TransitionTechnique,
  type ListPageMeta,
  type NamedRef,
  type FolderRef,
  type TrackExternalIds,
  type CreateTrackInput,
  type UpdateTrackInput,
  type NamedNode,
  type FolderNode,
  type TrackNode,
  type TrackSummary,
  type TrackDetail,
  type CreateTrackResult,
  type LibraryStats,
  type TrackSortField,
  type ListSortOrder,
  type ListTracksInput,
  type ListTracksResult,
  type ListVocabInput,
  type TransitionEdgeSummary,
  type RankableNeighbor,
  type FlatNeighborhoodNeighbor,
  type NeighborhoodNeighbor,
  type TrackNeighborhood,
  type TransitionEndpointSummary,
  type TransitionRecord,
  type TransitionProposalReview,
  type TransitionListItem,
  type CreateTransitionInput,
  type UpdateTransitionInput,
  type TransitionSortField,
  type TransitionSortOrder,
  type TransitionSourceFilter,
  type ListTransitionsInput,
  type ListTransitionsResult,
  type CommitTransitionInput,
  type CommitTransitionResult,
  listSequences,
  getSequenceDetail,
  createSequence,
  updateSequence,
  deleteSequence,
  listSequenceReferrers,
  addSequenceStep,
  updateSequenceStep,
  deleteSequenceStep,
  reorderSequence,
  detachSequenceStep,
  createSequenceAlternate,
  updateSequenceAlternate,
  deleteSequenceAlternate,
  createSequenceVersion,
  updateSequenceVersion,
  deleteSequenceVersion,
  type GapState,
  type SequenceRecord,
  type SequenceStep,
  type SequenceAlternate,
  type SequenceVersion,
  type ExpandedSequenceEntry,
  type SequenceExpansion,
  type SequenceDetail,
  type ListSequencesInput,
  type ListSequencesResult,
  type SequenceTrailSeed,
  type CreateSequenceInput,
  type UpdateSequenceInput,
  type AddSequenceStepInput,
  type UpdateSequenceStepInput,
  type CreateSequenceAlternateInput,
  type UpdateSequenceAlternateInput,
  type CreateSequenceVersionInput,
  type UpdateSequenceVersionInput,
  type GetSequenceDetailOptions,
  type SequenceReferrer,
} from "./music";
